#!/bin/bash

set -o pipefail &&
  xcodebuild \
    -scheme "SimpleNotesUITests" \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
    test \
  | bundle exec xcpretty \
    --color
