#!/bin/bash

set -o pipefail &&
  xcodebuild \
    -scheme "SimpleNotes" \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
    test \
  | bundle exec xcpretty \
		--test \
    --color
